name: sims_ppob_ainul_muhlasin
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  dio: ^5.7.0
  provider: ^6.1.2
  sizer: ^3.0.4
  flutter_svg: ^2.0.16
  flutter_form_builder: ^9.5.0
  intl: ^0.19.0
  path_provider: ^2.1.5
  hive_generator: ^2.0.1
  shared_preferences: ^2.3.4
  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0

flutter_gen:
  output: lib/shared/resources/gen/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - lib/shared/resources/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/shared/resources/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: lib/shared/resources/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: lib/shared/resources/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/shared/resources/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: lib/shared/resources/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/shared/resources/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: lib/shared/resources/fonts/Montserrat-Light.ttf
          weight: 300
